# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Shopify Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "Mobile-Buy-SDK"

  # Pods for Shopify Demo

end
